# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-07 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='pass', max_length=50),
            preserve_default=False,
        ),
    ]
